CREATE TABLE Sensor(
                       id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       name VARCHAR (30) UNIQUE NOT NULL
);

CREATE TABLE Measurement(
                            id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            sensor_id INT REFERENCES Sensor(id) ON DELETE SET NULL,
                            value NUMERIC (4, 1) NOT NULL CHECK (value >= -100 AND value <= 100),
                            raining BOOLEAN NOT NULL,
                            time TIMESTAMP
);

DROP TABLE Measurement;
DROP TABLE Sensor;
