DROP TABLE Measurement;
DROP TABLE Sensor;

CREATE TABLE Sensor
(
    id   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(30) UNIQUE NOT NULL
);

CREATE TABLE Measurement
(
    id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sensor_id   INT REFERENCES Sensor (id) ON DELETE CASCADE,
    temperature NUMERIC(4, 1) NOT NULL CHECK (temperature >= -100 AND temperature <= 100),
    raining     BOOLEAN       NOT NULL,
    time        TIMESTAMP
);